services:
  postgresql:
    image: postgres
    container_name: postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes: 
      - ./Database/postgres-data:/var/lib/postgresql/data
      - ./Database/Scripts/create_url.sql:/docker-entrypoint-initdb.d/create_url.sql
      - ./Database/Scripts/url_insert.sql:/docker-entrypoint-initdb.d/url_insert.sql
  shorturl_webapi:
    container_name: shorturl_webapi
    links:
      - postgresql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgresql
    build:
      context: .
      dockerfile: ./ShortUrlWebApi/Dockerfile
    ports:
      - "8000:80"
  shorturl_webapp:
    container_name: shorturl_webapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: ./ShortUrlWebApp/Dockerfile
    ports:
      - "9000:80"